###
GET http://localhost:8000/store

###
GET http://localhost:8000/store/

###
GET https://web-services-mdu8.onrender.com/store


###
POST https://web-services-mdu8.onrender.com/store HTTP/1.1
content-type:application/json

{"firstName":"billy", "lastName":"bob", "email":"billybob@gmail.com", "favoriteColor":"Blue", "birthday":"01/01/2000"}


###
PUT https://web-services-mdu8.onrender.com/store/6455489c79adf4d1f6953375 HTTP/1.1
content-type: application/json

{"firstName":"Bob", "lastName":"Billy", "email":"bobbilly@gmail.com", "favoriteColor":"Blue", "birthday":"02/21/1960"}

###
DELETE https://web-services-mdu8.onrender.com/store/6455489c79adf4d1f6953375 HTTP/1.1

###
https://web-services-mdu8.onrender.com/api-docs

###
http://localhost:8000/api-docs


