###
GET http://localhost:8000/store

###
GET http://localhost:8000/store/

###
GET https://web-services-mdu8.onrender.com/store


###
POST http://localhost:8000/store HTTP/1.1
content-type:application/json

{"itemName": "curry blocks", "itemCost": "5.99", "itemQuanityInStock": "56", "vendorID": "JP011", "vendorLocation": "Tokyo, Japan", "itemImagePath": "...", "itemAlt": "curry blocks"}


###
PUT https://web-services-mdu8.onrender.com/store/64698724263bdd00beb2e1f7 HTTP/1.1
content-type: application/json

{"itemName": "curry blocks", "itemCost": "5.99", "itemQuanityInStock": "6", "vendorID": "JP011", "vendorLocation": "Tokyo, Japan", "itemImagePath": "...", "itemAlt": "curry blocks"}

###
DELETE https://web-services-mdu8.onrender.com/store/64698724263bdd00beb2e1f7 HTTP/1.1

###
https://web-services-mdu8.onrender.com/api-docs

###
http://localhost:8000/api-docs


